# This file will be included by the Makefile under the project directory.
float_CFLAGS := -m32 -fno-builtin -I$(LIB_COMMON_DIR)
FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

$(FLOAT_OBJ): $(LIB_COMMON_DIR)/FLOAT.h $(LIB_COMMON_DIR)/FLOAT.c
	mkdir -p obj/lib-common
	gcc -c FLOAT.c FLOAT.h -o obj/lib-common/FLOAT.o $(float_CFLAGS)
